version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  exclusions:
    generated: strict

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
